export const IMAGES = {
   logo: require('../assets/images/Logo.png'),
};

export const ICONS = {
  
   bed: require('../assets/icons/bed.png'),
   home: require('../assets/icons/home.png'),
   facebook: require('../assets/icons/facebook.png'),
   google: require('../assets/icons/google.png'),
   ellipse: require('../assets/icons/ellipse.png'),
   ellipse2: require('../assets/icons/ellipse2.png'),
   ellipse3: require('../assets/icons/ellipse3.png'),
   ellipse4: require('../assets/icons/ellipse4.png'),
   logo: require('../assets/icons/logo.png'),
   Splash_image: require('../assets/icons/Splash_image.png'),
   arrow: require('../assets/icons/arrow.png'),
   intro: require('../assets/icons/intro.png'),
   home: require('../assets/icons/home.png'),
   categories: require('../assets/icons/categories.png'),
   favourities: require('../assets/icons/favourities.png'),
   notifications: require('../assets/icons/notifications.png'),
   cart: require('../assets/icons/cart.png'),
   logo1: require('../assets/icons/logo1.png'),
   user: require('../assets/icons/user.png'),
   camera: require('../assets/icons/camera.png'),
   menu: require('../assets/icons/menu.png'),
   location: require('../assets/icons/location.png'),
   search: require('../assets/icons/search.png'),
   carouselone: require('../assets/icons/carouselone.png'),
   carouseltwo: require('../assets/icons/carouseltwo.png'),
   bread: require('../assets/icons/bread.png'),
   milk: require('../assets/icons/milk.png'),
   cornflakes: require('../assets/icons/cornflakes.png'),
   cornflakes2: require('../assets/icons/cornflakes2.png'),
   downward_arrow: require('../assets/icons/downward_arrow.png'),
   order: require('../assets/icons/order.png'),
   change_password: require('../assets/icons/change_password.png'),
   user1: require('../assets/icons/user1.png'),
   rightarrow: require('../assets/icons/right-arrow.png'),
   wallet: require('../assets/icons/wallet.png'),
   left_arrow: require('../assets/icons/left_arrow.png'),
   previous: require('../assets/icons/previous.png'),
   star: require('../assets/icons/star.png'),
   heart: require('../assets/icons/heart.png'),
   cart1: require('../assets/icons/cart1.png'),
   carouselthree: require('../assets/icons/carouselthree.png'),
   delete: require('../assets/icons/delete.png'),
   discount: require('../assets/icons/discount.png'),
   dotted_line:require('../assets/icons/dotted_line.png'),
   cornflakes_backside: require('../assets/icons/cornflakes_backside.png'),
   cornflakes_sideview: require('../assets/icons/cornflakes_sideview.png'),
   recipe: require('../assets/icons/recipe.png'),
   coin: require('../assets/icons/coin.png'),
   filter: require('../assets/icons/filter.png'),
   right_arrow: require('../assets/icons/right_arrow.png'),
   share: require('../assets/icons/share.png'),
   help: require('../assets/icons/help.png'),
   recipe: require('../assets/icons/recipe.png'),
   recipe2: require('../assets/icons/recipe2.png'),
   recipe_item: require('../assets/icons/recipe_item.png'),
   recipe_item1: require('../assets/icons/recipe_item1.png'),
   recipe_item2: require('../assets/icons/recipe_item2.png'),
   recipe_item3: require('../assets/icons/recipe_item3.png'),
   dot: require('../assets/icons/dot.png'),
   meyonnaise: require('../assets/icons/meyonnaise.png'),
   burger_patty: require('../assets/icons/burger_patty.png'),
   amul: require('../assets/icons/amul.png'),
   snacks: require('../assets/icons/snacks.png'),
   wallet_coin: require('../assets/icons/wallet_coin.png'),
   info: require('../assets/icons/info.png'),
   buyandearn: require('../assets/icons/buyandearn.png'),
   deposit: require('../assets/icons/deposit.png'),
   transaction_history: require('../assets/icons/transaction_history.png'),
   cross: require('../assets/icons/cross.png'),
   referandearn: require('../assets/icons/referandearn.png'),
   noodles: require('../assets/icons/noodles.jpeg'),
   pasta: require('../assets/icons/pasta.png'),
   moreishbread: require('../assets/icons/moreishbread.png'),
   organicbread: require('../assets/icons/organicbread.png'),
   ryebread: require('../assets/icons/ryebread.jpg'),
   streetbread: require('../assets/icons/streetbread.png'),
   multigrainbread: require('../assets/icons/multigrainbread.jpg'),
   info2: require('../assets/icons/info2.png'),
   paytm: require('../assets/icons/paytm.png'),
   mobikwik: require('../assets/icons/mobikwik.png'),
   standard_chatered: require('../assets/icons/standard_chatered.png'),
   phonepe: require('../assets/icons/phonepe.png'),
   community_share: require('../assets/icons/community_share.png'),
   member_card: require('../assets/icons/member_card.png'),
   whatsapp: require('../assets/icons/whatsapp.png'),
   multiuser: require('../assets/icons/multiuser.png'),
   tick: require('../assets/icons/tick.png'),
   giftbox: require('../assets/icons/giftbox.png'),
   mail: require('../assets/icons/mail.png'),
   copy: require('../assets/icons/copy.png'),
   orangebg: require('../assets/icons/orangebg.png'),
   referlogo: require('../assets/icons/referlogo.png'),
   back: require('../assets/icons/back.png'),
   cart2: require('../assets/icons/cart2.png'),
   login: require('../assets/icons/login.png'),
   address_book: require('../assets/icons/address_book.png'),
   photo: require('../assets/icons/photo.png'),

};

export const FONTS = {
  
   PlayfairDisplayBlack: 'PlayfairDisplay-Black',
   RubikBold: 'Rubik-Bold',
   Hind: 'Hind-Medium',
};

export const COLORS = {
  
};
